apiVersion: v1
kind: Pod
metadata:
  name: app-readinessprob
spec:
  containers:
  - name: app
    image: gcr.io/k8s-k3s/demo:v2.0.0
    ports:
    - containerPort: 8000
      name: http
    readinessProbe:
      httpGet:
        path: /ready
        port: http
      initialDelaySeconds: 0
      periodSeconds: 2
      successThreshold: 1
      failureThreshold: 3
    livenessProbe:
      httpGet:
        path: /ready
        port: http
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
